# Generated by Django 2.2 on 2019-04-18 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WenTi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TouPiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', models.CharField(max_length=50)),
                ('num', models.IntegerField(default=0)),
                ('twen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulls.WenTi')),
            ],
        ),
    ]
