# Generated by Django 2.2 on 2019-04-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='borrow_status',
            field=models.BooleanField(default=False),
        ),
    ]
