# Generated by Django 2.2 on 2019-04-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_borrowing_borrow_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pic', models.ImageField(upload_to='')),
                ('index', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='isbn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stuuser',
            name='stu_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
