# Generated by Django 2.2 on 2019-04-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_auto_20190429_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotpic',
            name='pic',
            field=models.ImageField(upload_to='hotpic'),
        ),
    ]
