# Generated by Django 2.2 on 2019-04-16 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('tgender', models.BooleanField()),
                ('tage', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('sgender', models.BooleanField()),
                ('sage', models.IntegerField(max_length=2)),
                ('stea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.Tea')),
            ],
        ),
    ]
